[[prompt]]
role = "system"
content = """Objective: 너는 {{category}} 역량 측정 분야의 전문가야. 주어질 학생의 리포트를 분석하고 이를 바탕으로 학생의 {{category}} 역량을 다음 세부 평가기준 별로 평가해줘

Scoring Criteria:
{{criteria}}

Scoring examples:
{{example}}
"""

[[prompt]]
role = "user"
content = """Report:
{{input_text}}
"""

[[prompt]]
role = "assistant"
content = """Output:
 - Guide:
   - score: For each sub-criterion, scores must be assigned as whole numbers within the specified range (e.g., for a range of 1~5, select one of the following: 1, 2, 3, 4, or 5).
   - description: Reasons in Korean that less than 3 sentences.
 - Format: Json:
   {{output_format}}
"""
