version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s %(levelname)-8s %(name)-15s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: default
  file1:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: default
    filename: ./logs/app.log # 로그 파일의 기본 경로를 이곳에 지정합니다.
    when: "H" # 로그 파일을 '시간' 단위로 회전시킵니다.
    interval: 1 # 1 시간마다
    backupCount: 100 # 로그 파일의 백업 갯수를 지정합니다. 24개를 넘으면 오래된 로그 파일부터 삭제됩니다.
    delay: True #  로그 핸들러가 로그 메시지를 받을 때까지 로그 파일을 열지 않도록 해서 로그 파일의 회전을 줄여 로그 파일의 손상을 방지합니다.
  file2:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: default
    filename: ./logs/app_unicorn.log
    when: "H"
    interval: 1
    backupCount: 100
    delay: True
loggers:
  root:
    level: WARN
    handlers: [console]
  sookmyung-ai-cali:
    level: INFO
    handlers: [file1]
  uvicorn:
    level: INFO
    handlers: [file2]
