category_name_kor = "의사소통"

[[criteria]]
title_eng = "Content"
title_kor = "내용의 적절성"
elements = [
    "(중심 내용의 명확성) 글의 중심 내용이 명확하다",
    "(중심 내용의 구체성) 글의 중심 내용이 구체적이다",
    "(내용의 독창성) 글의 내용이 독창적이다",
    "(내용의 풍부성) 글의 내용을 뒷받침하는 근거나 예시가 다양하게 제시되어 있다.",
    "(주제의 명료성) 저자의 의도를 분명하게 제시한다",
    "(내용의 일관성) 글의 전체 내용에 일관성이 있다"
]

[[criteria]]
title_eng = "Structure"
title_kor = "조직의 효과성"
elements = [
    "(글 구조의 적절성) 글의 구조가 글의 목적에 부합한다.",
    "(문단 간 조직의 적절성) 문단과 문단 간 역할이 분명하다",
    "(문단 내 조직의 적절성) 문단 내 중심 문장과 뒷받침 문장이 명료하게 드러나있다.",
    "(내용 전개의 적절성) 필요한 정보가 유기적으로 배열되어 있다"
]

[[criteria]]
title_eng = "Grammar"
title_kor = "어법의 정확성"
elements = [
    "(맞춤법) 맞춤법과 띄어쓰기가 지켜지고 있다",
    "(어법) 어법을 잘 지키고 있다",
    "(문장의 간결성) 이해하기 쉽게 문장을 작성하였다"
]
