credentials:
  usernames:
    tester:
      email: tester@gmail.com
      name: tester
      password: $2b$12$xODRc4dPVqy2X8G2GryAJ.3GngUHtqFHKPrvk5NdDTlpAhMCmElw2
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$YDuhUVguqkES8AM9ivlL9OYzQcIPDGyG.FxaeduWl9WYVJaTmCaBu
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
    - melsby@gmail.com
